# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/dasha/CLionProjects/PSE-gtest/MetroSimulatie

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/dasha/CLionProjects/PSE-gtest/MetroSimulatie

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/dasha/CLionProjects/PSE-gtest/MetroSimulatie/CMakeFiles /mnt/c/Users/dasha/CLionProjects/PSE-gtest/MetroSimulatie/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/dasha/CLionProjects/PSE-gtest/MetroSimulatie/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testing_tool

# Build rule for target.
testing_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testing_tool
.PHONY : testing_tool

# fast build rule for target.
testing_tool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/build
.PHONY : testing_tool/fast

#=============================================================================
# Target rules for targets named main_executable

# Build rule for target.
main_executable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_executable
.PHONY : main_executable

# fast build rule for target.
main_executable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/build
.PHONY : main_executable/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f gtest/googlemock/CMakeFiles/gmock_main.dir/build.make gtest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f gtest/googlemock/CMakeFiles/gmock.dir/build.make gtest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f gtest/googletest/CMakeFiles/gtest_main.dir/build.make gtest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f gtest/googletest/CMakeFiles/gtest.dir/build.make gtest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

components/metronet/Metronet.o: components/metronet/Metronet.cpp.o

.PHONY : components/metronet/Metronet.o

# target to build an object file
components/metronet/Metronet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/Metronet.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/Metronet.cpp.o
.PHONY : components/metronet/Metronet.cpp.o

components/metronet/Metronet.i: components/metronet/Metronet.cpp.i

.PHONY : components/metronet/Metronet.i

# target to preprocess a source file
components/metronet/Metronet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/Metronet.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/Metronet.cpp.i
.PHONY : components/metronet/Metronet.cpp.i

components/metronet/Metronet.s: components/metronet/Metronet.cpp.s

.PHONY : components/metronet/Metronet.s

# target to generate assembly for a file
components/metronet/Metronet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/Metronet.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/Metronet.cpp.s
.PHONY : components/metronet/Metronet.cpp.s

components/metronet/MetronetExporter.o: components/metronet/MetronetExporter.cpp.o

.PHONY : components/metronet/MetronetExporter.o

# target to build an object file
components/metronet/MetronetExporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetExporter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetExporter.cpp.o
.PHONY : components/metronet/MetronetExporter.cpp.o

components/metronet/MetronetExporter.i: components/metronet/MetronetExporter.cpp.i

.PHONY : components/metronet/MetronetExporter.i

# target to preprocess a source file
components/metronet/MetronetExporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetExporter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetExporter.cpp.i
.PHONY : components/metronet/MetronetExporter.cpp.i

components/metronet/MetronetExporter.s: components/metronet/MetronetExporter.cpp.s

.PHONY : components/metronet/MetronetExporter.s

# target to generate assembly for a file
components/metronet/MetronetExporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetExporter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetExporter.cpp.s
.PHONY : components/metronet/MetronetExporter.cpp.s

components/metronet/MetronetImporter.o: components/metronet/MetronetImporter.cpp.o

.PHONY : components/metronet/MetronetImporter.o

# target to build an object file
components/metronet/MetronetImporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetImporter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetImporter.cpp.o
.PHONY : components/metronet/MetronetImporter.cpp.o

components/metronet/MetronetImporter.i: components/metronet/MetronetImporter.cpp.i

.PHONY : components/metronet/MetronetImporter.i

# target to preprocess a source file
components/metronet/MetronetImporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetImporter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetImporter.cpp.i
.PHONY : components/metronet/MetronetImporter.cpp.i

components/metronet/MetronetImporter.s: components/metronet/MetronetImporter.cpp.s

.PHONY : components/metronet/MetronetImporter.s

# target to generate assembly for a file
components/metronet/MetronetImporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetImporter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetImporter.cpp.s
.PHONY : components/metronet/MetronetImporter.cpp.s

components/metronet/MetronetValidator.o: components/metronet/MetronetValidator.cpp.o

.PHONY : components/metronet/MetronetValidator.o

# target to build an object file
components/metronet/MetronetValidator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetValidator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetValidator.cpp.o
.PHONY : components/metronet/MetronetValidator.cpp.o

components/metronet/MetronetValidator.i: components/metronet/MetronetValidator.cpp.i

.PHONY : components/metronet/MetronetValidator.i

# target to preprocess a source file
components/metronet/MetronetValidator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetValidator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetValidator.cpp.i
.PHONY : components/metronet/MetronetValidator.cpp.i

components/metronet/MetronetValidator.s: components/metronet/MetronetValidator.cpp.s

.PHONY : components/metronet/MetronetValidator.s

# target to generate assembly for a file
components/metronet/MetronetValidator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/metronet/MetronetValidator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/metronet/MetronetValidator.cpp.s
.PHONY : components/metronet/MetronetValidator.cpp.s

components/station/Station.o: components/station/Station.cpp.o

.PHONY : components/station/Station.o

# target to build an object file
components/station/Station.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/station/Station.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/station/Station.cpp.o
.PHONY : components/station/Station.cpp.o

components/station/Station.i: components/station/Station.cpp.i

.PHONY : components/station/Station.i

# target to preprocess a source file
components/station/Station.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/station/Station.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/station/Station.cpp.i
.PHONY : components/station/Station.cpp.i

components/station/Station.s: components/station/Station.cpp.s

.PHONY : components/station/Station.s

# target to generate assembly for a file
components/station/Station.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/station/Station.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/station/Station.cpp.s
.PHONY : components/station/Station.cpp.s

components/tram/Tram.o: components/tram/Tram.cpp.o

.PHONY : components/tram/Tram.o

# target to build an object file
components/tram/Tram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/tram/Tram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/tram/Tram.cpp.o
.PHONY : components/tram/Tram.cpp.o

components/tram/Tram.i: components/tram/Tram.cpp.i

.PHONY : components/tram/Tram.i

# target to preprocess a source file
components/tram/Tram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/tram/Tram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/tram/Tram.cpp.i
.PHONY : components/tram/Tram.cpp.i

components/tram/Tram.s: components/tram/Tram.cpp.s

.PHONY : components/tram/Tram.s

# target to generate assembly for a file
components/tram/Tram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/components/tram/Tram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/components/tram/Tram.cpp.s
.PHONY : components/tram/Tram.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/main.cpp.s
.PHONY : main.cpp.s

tests/tests_main.o: tests/tests_main.cpp.o

.PHONY : tests/tests_main.o

# target to build an object file
tests/tests_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/tests_main.cpp.o
.PHONY : tests/tests_main.cpp.o

tests/tests_main.i: tests/tests_main.cpp.i

.PHONY : tests/tests_main.i

# target to preprocess a source file
tests/tests_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/tests_main.cpp.i
.PHONY : tests/tests_main.cpp.i

tests/tests_main.s: tests/tests_main.cpp.s

.PHONY : tests/tests_main.s

# target to generate assembly for a file
tests/tests_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/tests_main.cpp.s
.PHONY : tests/tests_main.cpp.s

tests/unit/metronet/MetronetDomainTests.o: tests/unit/metronet/MetronetDomainTests.cpp.o

.PHONY : tests/unit/metronet/MetronetDomainTests.o

# target to build an object file
tests/unit/metronet/MetronetDomainTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetDomainTests.cpp.o
.PHONY : tests/unit/metronet/MetronetDomainTests.cpp.o

tests/unit/metronet/MetronetDomainTests.i: tests/unit/metronet/MetronetDomainTests.cpp.i

.PHONY : tests/unit/metronet/MetronetDomainTests.i

# target to preprocess a source file
tests/unit/metronet/MetronetDomainTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetDomainTests.cpp.i
.PHONY : tests/unit/metronet/MetronetDomainTests.cpp.i

tests/unit/metronet/MetronetDomainTests.s: tests/unit/metronet/MetronetDomainTests.cpp.s

.PHONY : tests/unit/metronet/MetronetDomainTests.s

# target to generate assembly for a file
tests/unit/metronet/MetronetDomainTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetDomainTests.cpp.s
.PHONY : tests/unit/metronet/MetronetDomainTests.cpp.s

tests/unit/metronet/MetronetInputTests.o: tests/unit/metronet/MetronetInputTests.cpp.o

.PHONY : tests/unit/metronet/MetronetInputTests.o

# target to build an object file
tests/unit/metronet/MetronetInputTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetInputTests.cpp.o
.PHONY : tests/unit/metronet/MetronetInputTests.cpp.o

tests/unit/metronet/MetronetInputTests.i: tests/unit/metronet/MetronetInputTests.cpp.i

.PHONY : tests/unit/metronet/MetronetInputTests.i

# target to preprocess a source file
tests/unit/metronet/MetronetInputTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetInputTests.cpp.i
.PHONY : tests/unit/metronet/MetronetInputTests.cpp.i

tests/unit/metronet/MetronetInputTests.s: tests/unit/metronet/MetronetInputTests.cpp.s

.PHONY : tests/unit/metronet/MetronetInputTests.s

# target to generate assembly for a file
tests/unit/metronet/MetronetInputTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetInputTests.cpp.s
.PHONY : tests/unit/metronet/MetronetInputTests.cpp.s

tests/unit/metronet/MetronetOutputTests.o: tests/unit/metronet/MetronetOutputTests.cpp.o

.PHONY : tests/unit/metronet/MetronetOutputTests.o

# target to build an object file
tests/unit/metronet/MetronetOutputTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetOutputTests.cpp.o
.PHONY : tests/unit/metronet/MetronetOutputTests.cpp.o

tests/unit/metronet/MetronetOutputTests.i: tests/unit/metronet/MetronetOutputTests.cpp.i

.PHONY : tests/unit/metronet/MetronetOutputTests.i

# target to preprocess a source file
tests/unit/metronet/MetronetOutputTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetOutputTests.cpp.i
.PHONY : tests/unit/metronet/MetronetOutputTests.cpp.i

tests/unit/metronet/MetronetOutputTests.s: tests/unit/metronet/MetronetOutputTests.cpp.s

.PHONY : tests/unit/metronet/MetronetOutputTests.s

# target to generate assembly for a file
tests/unit/metronet/MetronetOutputTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/metronet/MetronetOutputTests.cpp.s
.PHONY : tests/unit/metronet/MetronetOutputTests.cpp.s

tests/unit/station/StationDomainTests.o: tests/unit/station/StationDomainTests.cpp.o

.PHONY : tests/unit/station/StationDomainTests.o

# target to build an object file
tests/unit/station/StationDomainTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/station/StationDomainTests.cpp.o
.PHONY : tests/unit/station/StationDomainTests.cpp.o

tests/unit/station/StationDomainTests.i: tests/unit/station/StationDomainTests.cpp.i

.PHONY : tests/unit/station/StationDomainTests.i

# target to preprocess a source file
tests/unit/station/StationDomainTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/station/StationDomainTests.cpp.i
.PHONY : tests/unit/station/StationDomainTests.cpp.i

tests/unit/station/StationDomainTests.s: tests/unit/station/StationDomainTests.cpp.s

.PHONY : tests/unit/station/StationDomainTests.s

# target to generate assembly for a file
tests/unit/station/StationDomainTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/station/StationDomainTests.cpp.s
.PHONY : tests/unit/station/StationDomainTests.cpp.s

tests/unit/tram/TramDomainTests.o: tests/unit/tram/TramDomainTests.cpp.o

.PHONY : tests/unit/tram/TramDomainTests.o

# target to build an object file
tests/unit/tram/TramDomainTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/tram/TramDomainTests.cpp.o
.PHONY : tests/unit/tram/TramDomainTests.cpp.o

tests/unit/tram/TramDomainTests.i: tests/unit/tram/TramDomainTests.cpp.i

.PHONY : tests/unit/tram/TramDomainTests.i

# target to preprocess a source file
tests/unit/tram/TramDomainTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/tram/TramDomainTests.cpp.i
.PHONY : tests/unit/tram/TramDomainTests.cpp.i

tests/unit/tram/TramDomainTests.s: tests/unit/tram/TramDomainTests.cpp.s

.PHONY : tests/unit/tram/TramDomainTests.s

# target to generate assembly for a file
tests/unit/tram/TramDomainTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tests/unit/tram/TramDomainTests.cpp.s
.PHONY : tests/unit/tram/TramDomainTests.cpp.s

tools/tinyxml/tinystr.o: tools/tinyxml/tinystr.cpp.o

.PHONY : tools/tinyxml/tinystr.o

# target to build an object file
tools/tinyxml/tinystr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinystr.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinystr.cpp.o
.PHONY : tools/tinyxml/tinystr.cpp.o

tools/tinyxml/tinystr.i: tools/tinyxml/tinystr.cpp.i

.PHONY : tools/tinyxml/tinystr.i

# target to preprocess a source file
tools/tinyxml/tinystr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinystr.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinystr.cpp.i
.PHONY : tools/tinyxml/tinystr.cpp.i

tools/tinyxml/tinystr.s: tools/tinyxml/tinystr.cpp.s

.PHONY : tools/tinyxml/tinystr.s

# target to generate assembly for a file
tools/tinyxml/tinystr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinystr.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinystr.cpp.s
.PHONY : tools/tinyxml/tinystr.cpp.s

tools/tinyxml/tinyxml.o: tools/tinyxml/tinyxml.cpp.o

.PHONY : tools/tinyxml/tinyxml.o

# target to build an object file
tools/tinyxml/tinyxml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxml.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxml.cpp.o
.PHONY : tools/tinyxml/tinyxml.cpp.o

tools/tinyxml/tinyxml.i: tools/tinyxml/tinyxml.cpp.i

.PHONY : tools/tinyxml/tinyxml.i

# target to preprocess a source file
tools/tinyxml/tinyxml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxml.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxml.cpp.i
.PHONY : tools/tinyxml/tinyxml.cpp.i

tools/tinyxml/tinyxml.s: tools/tinyxml/tinyxml.cpp.s

.PHONY : tools/tinyxml/tinyxml.s

# target to generate assembly for a file
tools/tinyxml/tinyxml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxml.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxml.cpp.s
.PHONY : tools/tinyxml/tinyxml.cpp.s

tools/tinyxml/tinyxmlerror.o: tools/tinyxml/tinyxmlerror.cpp.o

.PHONY : tools/tinyxml/tinyxmlerror.o

# target to build an object file
tools/tinyxml/tinyxmlerror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxmlerror.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxmlerror.cpp.o
.PHONY : tools/tinyxml/tinyxmlerror.cpp.o

tools/tinyxml/tinyxmlerror.i: tools/tinyxml/tinyxmlerror.cpp.i

.PHONY : tools/tinyxml/tinyxmlerror.i

# target to preprocess a source file
tools/tinyxml/tinyxmlerror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxmlerror.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxmlerror.cpp.i
.PHONY : tools/tinyxml/tinyxmlerror.cpp.i

tools/tinyxml/tinyxmlerror.s: tools/tinyxml/tinyxmlerror.cpp.s

.PHONY : tools/tinyxml/tinyxmlerror.s

# target to generate assembly for a file
tools/tinyxml/tinyxmlerror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxmlerror.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxmlerror.cpp.s
.PHONY : tools/tinyxml/tinyxmlerror.cpp.s

tools/tinyxml/tinyxmlparser.o: tools/tinyxml/tinyxmlparser.cpp.o

.PHONY : tools/tinyxml/tinyxmlparser.o

# target to build an object file
tools/tinyxml/tinyxmlparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxmlparser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxmlparser.cpp.o
.PHONY : tools/tinyxml/tinyxmlparser.cpp.o

tools/tinyxml/tinyxmlparser.i: tools/tinyxml/tinyxmlparser.cpp.i

.PHONY : tools/tinyxml/tinyxmlparser.i

# target to preprocess a source file
tools/tinyxml/tinyxmlparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxmlparser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxmlparser.cpp.i
.PHONY : tools/tinyxml/tinyxmlparser.cpp.i

tools/tinyxml/tinyxmlparser.s: tools/tinyxml/tinyxmlparser.cpp.s

.PHONY : tools/tinyxml/tinyxmlparser.s

# target to generate assembly for a file
tools/tinyxml/tinyxmlparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tools/tinyxml/tinyxmlparser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tools/tinyxml/tinyxmlparser.cpp.s
.PHONY : tools/tinyxml/tinyxmlparser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... main_executable"
	@echo "... testing_tool"
	@echo "... components/metronet/Metronet.o"
	@echo "... components/metronet/Metronet.i"
	@echo "... components/metronet/Metronet.s"
	@echo "... components/metronet/MetronetExporter.o"
	@echo "... components/metronet/MetronetExporter.i"
	@echo "... components/metronet/MetronetExporter.s"
	@echo "... components/metronet/MetronetImporter.o"
	@echo "... components/metronet/MetronetImporter.i"
	@echo "... components/metronet/MetronetImporter.s"
	@echo "... components/metronet/MetronetValidator.o"
	@echo "... components/metronet/MetronetValidator.i"
	@echo "... components/metronet/MetronetValidator.s"
	@echo "... components/station/Station.o"
	@echo "... components/station/Station.i"
	@echo "... components/station/Station.s"
	@echo "... components/tram/Tram.o"
	@echo "... components/tram/Tram.i"
	@echo "... components/tram/Tram.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tests/tests_main.o"
	@echo "... tests/tests_main.i"
	@echo "... tests/tests_main.s"
	@echo "... tests/unit/metronet/MetronetDomainTests.o"
	@echo "... tests/unit/metronet/MetronetDomainTests.i"
	@echo "... tests/unit/metronet/MetronetDomainTests.s"
	@echo "... tests/unit/metronet/MetronetInputTests.o"
	@echo "... tests/unit/metronet/MetronetInputTests.i"
	@echo "... tests/unit/metronet/MetronetInputTests.s"
	@echo "... tests/unit/metronet/MetronetOutputTests.o"
	@echo "... tests/unit/metronet/MetronetOutputTests.i"
	@echo "... tests/unit/metronet/MetronetOutputTests.s"
	@echo "... tests/unit/station/StationDomainTests.o"
	@echo "... tests/unit/station/StationDomainTests.i"
	@echo "... tests/unit/station/StationDomainTests.s"
	@echo "... tests/unit/tram/TramDomainTests.o"
	@echo "... tests/unit/tram/TramDomainTests.i"
	@echo "... tests/unit/tram/TramDomainTests.s"
	@echo "... tools/tinyxml/tinystr.o"
	@echo "... tools/tinyxml/tinystr.i"
	@echo "... tools/tinyxml/tinystr.s"
	@echo "... tools/tinyxml/tinyxml.o"
	@echo "... tools/tinyxml/tinyxml.i"
	@echo "... tools/tinyxml/tinyxml.s"
	@echo "... tools/tinyxml/tinyxmlerror.o"
	@echo "... tools/tinyxml/tinyxmlerror.i"
	@echo "... tools/tinyxml/tinyxmlerror.s"
	@echo "... tools/tinyxml/tinyxmlparser.o"
	@echo "... tools/tinyxml/tinyxmlparser.i"
	@echo "... tools/tinyxml/tinyxmlparser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

