//
// Created by gruzi on 24/04/2023.
//

#ifndef PROJECT_SOFTWARE_PRACTICUM2_IMETROOBJECT_H
#define PROJECT_SOFTWARE_PRACTICUM2_IMETROOBJECT_H


class IMetroObject {};


#endif //PROJECT_SOFTWARE_PRACTICUM2_IMETROOBJECT_H
